import { Vec3 } from '../math/Vec3';
import { Mat4 } from '../math/Mat4';
import { Camera } from './Camera';
import { Portal } from '../noneuclideans/Portal';

export interface RenderBox {
    pos: Vec3;
    scale: Vec3;
    mult: number[];
    room: string;
}

export class Scene {
    public boxes: RenderBox[] = [];
    public portals: Portal[] = [];
    public activeRoom: string = 'A';

    addBox(box: RenderBox) {
        this.boxes.push(box);
    }

    addPortal(portal: Portal) {
        this.portals.push(portal);
    }

    updateTeleportation(camera: Camera) {
        for (const portal of this.portals) {
            const newRoom = portal.checkCrossing(camera, this.activeRoom);
            if (newRoom) {
                this.activeRoom = newRoom;
                break; // Only allow crossing one portal per frame
            }
        }
    }

    getRenderJobs(camera: Camera, maxDepth: number = 2) {
        const jobs: any[] = [];
        let textureCount = 0;

        // Recursive function to explore rooms from the inside out
        const buildRoom = (room: string, camPos: Vec3, depth: number, incomingPortal?: Portal): number => {
            if (depth === 0) return -1; // -1 means we hit the depth limit

            const models: any[] = [];
            const activePortals = this.portals.filter(p => p.roomA === room || p.roomB === room);

            // 1. Add standard room geometry
            this.boxes.filter(b => b.room === room).forEach(b => {
                models.push({ 
                    model: Mat4.multiply(Mat4.translation(b.pos), Mat4.scaling(b.scale)), 
                    mult: b.mult 
                });
            });

            // 2. Process inner portals
            activePortals.forEach(portal => {
                // Prevent infinite loops by not looking back through the portal we just came from
                if (portal === incomingPortal) return; 

                const isRoomA = room === portal.roomA;
                const currentPos = isRoomA ? portal.posA : portal.posB;
                const targetPos = isRoomA ? portal.posB : portal.posA;
                const virtualRoom = isRoomA ? portal.roomB : portal.roomA;

                const scaleX = portal.axis === 'X' ? 0.01 : portal.width;
                const scaleZ = portal.axis === 'X' ? portal.width : 0.01;
                const portalModelMatrix = Mat4.multiply(Mat4.translation(currentPos), Mat4.scaling([scaleX, portal.height, scaleZ]));

                // Shift the virtual camera
                const camOffset = Vec3.sub(camPos, currentPos);
                const virtualCamPos = Vec3.add(targetPos, camOffset);

                // RECURSION: Go one layer deeper! 
                const innerTextureIndex = buildRoom(virtualRoom, virtualCamPos, depth - 1, portal);

                if (innerTextureIndex === -1) {
                    // Depth limit reached: Cap it with a solid wall (stops the blue void)
                    models.push({ model: portalModelMatrix, mult: [0.8, 0.8, 0.8, 1.0] });
                } else {
                    // Link this portal quad to the texture generated by the deeper room
                    models.push({ model: portalModelMatrix, mult: [1, 1, 1, 1], portalIndex: innerTextureIndex });
                }
            });

            // 3. Create the Job
            if (!incomingPortal) {
                // If there's no incoming portal, this is the MAIN room (renders direct to canvas)
                jobs.push({ isMain: true, view: camera.getViewMatrix(), models });
                return -1;
            } else {
                // This is a VIRTUAL room (renders to a texture)
                const myTextureIndex = textureCount++;
                jobs.push({ isMain: false, targetIndex: myTextureIndex, view: camera.getVirtualViewMatrix(camPos), models });
                return myTextureIndex;
            }
        };

        // Kick off the recursion from the room the player is standing in
        buildRoom(this.activeRoom, camera.pos, maxDepth, undefined);

        return { jobs, totalTextures: textureCount };
    }
}